apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend
          image: image-registry.apps.2.rahti.csc.fi/sdx-assignment-nhantran/fastapi-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: mysql+pymysql://root:Baochau2903-@database-service:3306/medical_diagnosis_dba
            - name: SECRET_KEY
              value: supersecretkey
            - name: ALGORITHM
              value: HS256
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "7200"

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend-service
spec:
  selector:
    app: fastapi-backend
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fastapi-backend-route
spec:
  to:
    kind: Service
    name: fastapi-backend-service
  port:
    targetPort: 8000
  tls:
    termination: edge
